Yastvo/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from users import views as userViews
from django.contrib.auth import views as authViews
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('reg/', userViews.register, name = 'reg'),
    path('delivery/', include ('delivery.urls')),
    path('users/', authViews.LoginView.as_view(template_name= 'users/users.html'), name = 'users'),
    path('exit/', authViews.LogoutView.as_view(template_name= 'users/exit.html'), name = 'exit'),
    path('profile/', userViews.profile, name = 'profile'),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('payments/', include('payments.urls')),
]


urlpatterns += i18n_patterns (
    path('', include('main.urls')),
    path('reg/', userViews.register, name = 'reg'),
    path('delivery/', include ('delivery.urls')),
    path('users/', authViews.LoginView.as_view(template_name= 'users/users.html'), name = 'users'),
    path('exit/', authViews.LogoutView.as_view(template_name= 'users/exit.html'), name = 'exit'),
    path('profile/', userViews.profile, name = 'profile'),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/urls.py
"""This is urls.py in app main
It is created for main app and its parts
"""
from django.urls import path
from . import views
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    OrderSummaryView,
    CheckoutView,
    PaymentView,
    ShowMenuItem,
    ShowMenuDetailed,
    CreateDishes
    
)

urlpatterns = [
    path('', ShowMenuItem.as_view(), name = 'delivery'),
    path('<int:pk>', ShowMenuDetailed.as_view(), name = 'delivery-detailed' ),  
    path('add', CreateDishes.as_view(), name = 'add'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),
    path('delete', views.delete, name='delete'),
]

main/urls.py
"""This is urls.py in app main
It is created for main app and its parts
"""
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.index, name = 'home'),
    path('menu', views.menu, name = 'menu'),
    path('contacts', views.contacts, name = 'contacts'),
    
   ]

delivery/models.py
import sys
from PIL import Image
from io import BytesIO
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.utils.translation import gettext as _

 

LABEL = (
        ('',""),
        ('N', 'New'),
        ('BS', 'Best Seller')
)

CATEGORY = (
    ('B', _('Breakfast')),
    ('LC', _('Lunch')),
    ('SN', _('Snack')),
    ('D', _('Drinks')),
    ('SD', _('Salads')),
    ('DS',_('Desserts'))
)

class MenuItems (models.Model):
    item = models.CharField(_('Meal name'), max_length=50)
    category = models.CharField(_('Category'), choices=CATEGORY, max_length=2, default='B')
    label = models.CharField(_('Label'), choices=LABEL, max_length=2, blank=True, null=True)
    item_description = models.CharField(_('Meal description'), max_length=150)
    item_composition = models.CharField(_('Ingredients'), max_length=150)
    item_weight = models.FloatField(verbose_name=_('Net weight'))
    item_price = models.FloatField(verbose_name=_('Meal price'), default=100.00)
    item_discount = models.FloatField(verbose_name=_('Discounted price'), blank=True, null=True)
    item_calories = models.IntegerField(verbose_name=_('Calories'), default=100)
    item_image = models.ImageField(_('Meal image'), upload_to='goods')
    milk_added = models.BooleanField(verbose_name=_('Milk components added'), default=False)
    
    class Meta:
        verbose_name = _('Meal')
        verbose_name_plural = _('Meals')
    

    def __str__(self):
        return self.item


    def save(self, *args, **kwargs):
        item_image = self.item_image
        img = Image.open(item_image)
        new_img = img.convert('RGB')
        resized_new_img = new_img.resize((600, 600), Image.LANCZOS)
        filestream = BytesIO()
        resized_new_img.save(filestream, 'JPEG', quality=25)
        filestream.seek(0)
        name = '{}.{}'.format(*self.item_image.name.split('.'))
        self.item_image = InMemoryUploadedFile(
            filestream, 'ImageField', name, 'jpeg/image', len(filestream.getbuffer()), None
        )
        super().save(*args, **kwargs)
    

    def get_absolute_url(self):
         return reverse ('add')

    
    def get_add_to_cart_url(self):
        return reverse("add-to-cart", kwargs={
            "pk" : self.pk  
        })

    def get_remove_from_cart_url(self):
        return reverse("remove-from-cart", kwargs={
            "pk" : self.pk
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(MenuItems, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.item}"

    def get_total_item_price(self):
        return self.quantity * self.item.item_price

    def get_discount_item_price(self):
        return self.item.item_price - self.item.item_discount

    def get_amount_saved(self):
        return self.quantity * (self.item.item_price - self.item.item_discount)

    def get_total_price_with_discount(self):
        try:
            return self.quantity*(self.item.item_price - (self.item.item_price-self.item.item_discount))
        except:
            return self.quantity*(self.item.item_price)

    def get_final_price(self):
        if self.item.item_discount:
            return self.get_total_price_with_discount()
        return self.get_total_item_price()
    

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    checkout_address = models.ForeignKey(
        'CheckoutAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    def get_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class CheckoutAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100, default=user)
    last_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20, default=123)
    email = models.EmailField(max_length=25, default='email@email.com')
    
    def __str__(self):
        return self.user.username
    
           
class Payment(models.Model):
    stripe_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    

main/models.py
from django.db import models
from django.utils.translation import gettext as _

class Messages (models.Model):
    email = models.EmailField(_("Your email address"), max_length=50)
    subject = models.CharField(_('Email subject'), max_length=100)
    message = models.TextField(_('Email text'), max_length=1000)

    def __str__(self):
        return self.email

delivery/forms.py
from django import forms
from django.utils.translation import gettext as _
from .models import CATEGORY, LABEL, MenuItems

PAYMENT = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class AddDishesForm(forms.ModelForm):
    item = forms.CharField(max_length=50, widget=forms.TextInput(attrs=
    {'class':'form-control',
    'placeholder':_('Item name'),
    'id':'menuItem'
    }))

    category = forms.ChoiceField(choices=CATEGORY,required=True, widget=forms.Select (attrs={
    'class':'form-control',
    'id':'category'
    }))

    label = forms.ChoiceField(choices=LABEL, required=False, widget=forms.Select (attrs={
    'class':'form-control',
    'id':'label'
    }))

    item_description = forms.CharField(widget=forms.TextInput (attrs=
    {'class':'form-control',
    'placeholder':_('Item description'),
    'id':'itemDescription'
    }))
    item_composition = forms.CharField(widget=forms.TextInput (attrs=
    {'class':'form-control',
    'placeholder':_('Item composition'),
    'id':'itemComposition'
    }))
    item_weight = forms.FloatField(required=True, widget=forms.NumberInput(attrs={
    'class':'form-control',
    'id':'weight'
    }))

    item_price = forms.FloatField(required=True, widget=forms.NumberInput(attrs={
    'class':'form-control',
    'id':'price'
    }))
    item_discount = forms.FloatField(required=False, widget=forms.NumberInput(attrs={
    'class':'form-control',
    'id':'discount'
    }))
    item_calories = forms.FloatField(required=True, widget=forms.NumberInput(attrs={
    'class':'form-control',
    'id':'calories'
    }))
    item_image = forms.ImageField(widget=forms.FileInput)
    milk_added =forms.CheckboxInput(attrs={
         'class':'form-control',
        'id':'milk'
    })

    class Meta:
        model = MenuItems
        fields = ['item', 'category', 'label', 'item_description','item_composition','item_weight','item_price','item_discount','item_calories', 'item_image', 'milk_added']



class CheckoutForm(forms.Form):
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={
    'class': 'form-control',
    'placeholder': _('First name'), 
    'id': 'firstName', 
    }))

    last_name =  forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control',
    'placeholder': _('Last name'),
    'id': 'lastName', 
    }))

    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'email@email.com',
        'id': 'email',
        'type':'e-mail'

    }))
    street_address = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': _('Your address'),
        'id': 'address',
    }))

    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': _('Apartment or suite'),
        'id':'address2',
    }))

    phone_number = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control', 
        'placeholder':'+1(235)45-89-89',
        'id':'phone-number'
    }))

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT)

main/forms.py
from django.db import models
from django import forms
from django.forms import widgets
from .models import Messages
from django.utils.translation import gettext as _

class ContactForm(forms.ModelForm):

    email = models.EmailField(max_length=150)
    subject = models.CharField(max_length=150)
    message = forms.CharField(widget=forms.Textarea,max_length=1000, label=_("Your message"))

    class Meta:
        model = Messages
        fields = ['email', 'subject', 'message']

main/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from .forms import ContactForm
from django.http import HttpResponse
from django.contrib import messages
from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate

def index(request):
    return render(request, 'main/index.html')

def menu(request):
    return render(request, 'main/menu.html')


def contacts(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            messages.success(request, _('Message sent'))
            form.save()
            subject = _('Message from site')
            body = {
                'email' : form.cleaned_data['email'],
                'subject' : form.cleaned_data['subject'],
                'message' : form.cleaned_data['message'],
            }
            message = "\n".join(body.values())
            try:
                send_mail(subject=subject, message=message, from_email='demetriy.78@gmail.com', recipient_list=['demetriy.78@gmail.com'])
            except BadHeaderError:
                return HttpResponse(_('Incorrect header'))
            return redirect ('contacts')

    form = ContactForm()
    return render(request, "main/contacts.html", {'form': form})

main/templates/main/add-dishes.html
{% extends 'main/layout.html' %}
{% load i18n %}
{% block title %}
{% translate 'Adding dishes to menu' %}
{% endblock %}
{% block content %}

<div class="col-md-7 col-lg-8 mt-5">
  <form enctype="multipart/form-data" class="needs-validation" novalidate method="POST">
    {% csrf_token %}
    <div class="text-center">
      <h4 class="mb-5 ">{% translate 'Adding dishes to menu' %}</h4>
    </div>
    <div class="row g-3">
      <div class="col-12">
        <label for="item" class="form-label">{%translate 'Meal name' %}</label>
        {{form.item}}
        <div class="invalid-feedback">
          {% translate 'Valid meal name required.' %}
        </div>
      </div>

      <div class="col-sm-6">
        <label for="category" class="form-label"
          >{% translate 'Category' %}</label
        >
        {{ form.category }}
        <div class="invalid-feedback">{% translate 'Category required.' %}</div>
      </div>

      <div class="col-sm-6">
        <label for="label" class="form-label">{% translate 'Label' %}</label>
        {{ form.label }}
      </div>

      <div class="col-12">
        <label for="item_description" class="form-label"
          >{% translate 'Meal description' %}</label
        >
        {{ form.item_description }}
        <div class="invalid-feedback">
          {% translate 'Meal description needed.' %}
        </div>
      </div>

      <div class="col-12">
        <label for="item_composition" class="form-label"
          >{% translate 'Meal composition' %}</label
        >
        {{ form.item_composition }}
        <div class="invalid-feedback">
          {% translate 'Meal composition needed.' %}
        </div>
      </div>

      <div class="col-sm-6">
        <label for="weight" class="form-label">{% translate 'Weight' %}</label>
        {{ form.item_weight }}
        <div class="invalid-feedback">{% translate 'Weight needed.' %}</div>
      </div>

      <div class="col-sm-6">
        <label for="price" class="form-label">{% translate 'Price' %}</label>
        {{ form.item_price }}
        <div class="invalid-feedback">{% translate 'Price needed.' %}</div>
      </div>

      <div class="col-sm-6">
        <label for="price" class="form-label">{% translate 'Discount' %}</label>
        {{ form.item_discount }}
      </div>

      <div class="col-sm-6">
        <label for="calories" class="form-label"
          >{% translate 'Calories' %}</label
        >
        {{ form.item_calories }}
      </div>

      <div class="col-12">
        <label for="item_image" class="form-label"
          >{% translate 'Meal image' %}</label
        >
        {{ form.item_image }}
        <div class="invalid-feedback">{% translate 'Image needed.' %}</div>
      </div>

      <div class="col-sm-6">
        <label for="milk" class="form-label"
          >{% translate 'Contains milk' %}</label
        >
        {{ form.milk_added }}
      </div>
      <div class="text-center">
        <button class="btn greenBtn btn-lg mb-3 mx-auto" type="submit">
          {% translate 'Add meal to menu' %}
        </button>
      </div>
    </div>
  </form>
</div>

{% endblock %}

main/templates/main/contacts.html
{% extends 'main/layout.html' %}
{% load i18n %}
{% block title %}{% translate 'Our contacts' %}{% endblock %}

{% block content %}
<div class="container-fluid mt-5">
  <div class="row">
    <div class="col-12 col-lg-4 mt-5">
      <div class="d-flex justify-content-center">
        <form method="post" class="decor">
          <div class="form-left-decoration"></div>
          <div class="form-right-decoration"></div>
          <div class="container flex form-inner">
            <h3 class="text-center mb-3">{% translate 'Write us an email' %}</h3>
            {% csrf_token %}
            {{form.as_p}}
            <div class="d-flex justify-content-center">
              <input type="submit" value="{% translate 'Send' %}">
            </div>
          </div>
        </form>
      </div>
    </div>
   

    <div class="col-12 col-lg-4 mt-5" id="map">
      <style>
        #map {
            border: 2px solid green;
            border-radius: 20px;
            box-shadow: -10px 10px 0px rgba(0, 0, 0, 0.2);
            margin-top: 10%;
        }
    
        @media (min-width: 992px) {
            #map {
                height: 90%;
            }
        }
    
        @media (max-width: 768px) {
            #map {
                height: 400px;
            }
        }
    </style>
         
      <script>
          function initMap() {
              var location = {lat: 50.0647, lng: 19.9450};
              var map = new google.maps.Map(document.getElementById('map'), {
                  zoom: 14,
                  center: location
              });
              var marker = new google.maps.Marker({
                  position: location,
                  map: map
              });
          }
      </script>
      <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAcR0PMILbGgQ6DgF4bn_dL8zEFFFyJj74&callback=initMap"></script>
    </div>

    <div class="col-12 col-lg-4 mt-5 vegan">
      <h3>{% translate 'We have a rule:' %}</h3>
      <h4 style="text-align: center;">{% translate 'The food must be just-cooked' %} </h4>
      <p>{% translate 'All dishes are made "under knife", so, on your order! ' %} </p>
      <p>{% translate 'We have some food preparations, on our kitchen to speed up dish cooking, but if there are many orders, your order may be ready a bit longer' %}</p>
      <p>{% translate 'Please, tell us if You have allergy on some food components' %}</p>
      <p>{% translate 'We have delivery service "Cafe at your home!"' %}</p>
      <p class="text-center mb-3 vegan"><i class="fas fa-seedling">Vegan 100%</i></p>
      <i class="bi bi-telephone"><a href="tel:+4864458524">+4864458524</a></i> <br>
      <i class="bi bi-envelope-open"><a href="mailto:postmaster@yastvo.com"> postmaster@yastvo.com</a></i><br>
      <i class="bi bi-geo-alt-fill">Slava Ukraine!</i>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main/delivery-detailed.html
{% extends 'main/layout.html' %} 
{% load static %}
 {% load i18n %}
  {% block title %}
  {{title}}
  {%endblock %}
   {% block content %}

<div class="cart-button">
  <a
    class="btn btn-success rounded-pill-lg floating-button"
    href="{%url 'order-summary' %}"
    ><i class="bi-cart-fill">
      <span
        class="position-absolute top-0 start-100 trans-middle badge rounded-pill bg-danger"
        >{{ cart.items.count }}</span
      ></i
    >
  </a>
</div>

<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <div class="row">
    <div class="col-4">
      <img
            src="{{ object.item_image.url }}"
            class="bd-placeholder-img card-img-top rounded-circle"
          />
      </div>
      <div class="col-8">
        <div class="col-8">
        <h1 class="display-4 fw-bold text-center vegan position-relative">{{object.item}}<span class="fs-5 position-absolute top-0 start-100 translate-middle badge rounded-pill {% if object.label == 'N' %} bg-danger {% else %} bg-success {% endif %}">{{ object.get_label_display }} </span> </h1>
      </div>
        <h2 class="display-4 text-center"> {{object.item_description}}</h2>
        <h2 class="display-6"><strong>{% translate 'Meal composition: '%} </strong>{{object.item_composition}} </h2>
        <p class="fs-4 text-start"><strong>{% translate 'Weight:' %}</strong>{{object.item_weight}}</p>
        <p class="fs-4 text-start"><strong>{% translate 'Calories:' %} </strong>{{object.item_calories}}</p>
        <h2 class="display-5">{% translate 'Price: ' %}{% if object.item_discount %}<span class ="text-muted"><del>{{ object.item_price }}</del></span>
        <span class="text-danger">{{ object.item_discount }}</span>{% else %} <span>{{ object.item_price }}</span> {% endif %}
     


               {% if object.milk_added %}
              <!-- Button trigger modal -->
              <button
                type="button"
                class="btn btn-info"
                data-bs-toggle="modal"
                data-bs-target="#exampleModal"
              >
                <img
                  src="{% static 'main/img/svg/milk-bottle.svg' %}"
                  height="64"
                  width="auto"
                />
              </button>
              <!-- Modal -->
              <div
                class="modal fade"
                id="exampleModal"
                tabindex="-1"
                aria-labelledby="exampleModalLabel"
                aria-hidden="true"
              >
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title danger" id="exampleModalLabel">
                        {% translate 'Warning!' %}
                      </h5>
                      <button
                        type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"
                      ></button>
                    </div>
                    <div class="modal-body">
                      {% translate 'This product contains milk or milk components!' %}
                    </div>
                    <div class="modal-footer">
                      <button
                        type="button"
                        class="btn btn-success"
                        data-bs-dismiss="modal"
                      >
                        {% translate 'Close' %}
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              {% endif %}
            </div>

            <a
              href="{% url 'delivery' %}"
              class="btn lightGreenBtn btn-md my-0 p"
              >{% translate 'Back' %}</a
            >
          </div>
    
        </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    var myModal = document.getElementById("myModal");
    var myInput = document.getElementById("myInput");

    myModal.addEventListener("shown.bs.modal", function () {
      myInput.focus();
    });
  </script>

  {% endblock %}
</div>

main/templates/main/delivery.html
{% extends 'main/layout.html' %} 
{% load static %}
{% load i18n %}
{% block title %}{{title}}{% endblock %} 
{% block content %}

  <div class="cart-button">

    <a class="btn btn-success rounded-pill-lg floating-button" href="{%url 'order-summary' %}"
    ><i class="bi-cart-fill">
      <span class="position-absolute top-0 start-100 trans-middle badge rounded-pill bg-danger">{{ cart.items.count }}</i></span>
      </a
      >
  </div>
 
<div class="album py-5">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for dishes in food %}
      
      <div class="col">
        <div class="card border-light border border-0 h-100">
          <img
            src="{{ dishes.item_image.url }}"
            class="bd-placeholder-img bg-transparent card-img-top img-fluid rounded-circle"
          />
          <div class="card-body d-flex flex-column h-100">
            <h3 class="card-text mb-3">{{ dishes.item_description }}</h3>
            
            {% if dishes.item_discount %}
            <span>{% translate 'Price:' %}
              <del>{{ dishes.item_price }}</del>
            
            {{ dishes.item_discount}}</span>
            {% else %}
            <span>{% translate 'Price:' %} {{ dishes.item_price }}</span>
            {% endif %}

            <div class="btn-group mt-auto" role="group">
              {%if not user.is_authenticated %}              
              <a
                href="{%url 'reg' %}"
                class="btn btn-warning btn-md my-0 p"
                > {% translate 'Register to order!' %}
                
              </a>                    
              {% else %}
              <a
                href="{{ dishes.get_add_to_cart_url }}"
                class="btn greenBtn btn-md my-0 p"
                > {% translate 'Add to cart' %}
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
              {% endif %}
              <a
                href="{% url 'delivery-detailed' dishes.id%} "
                class="btn lightGreenBtn btn-md my-0 p"
                >{% translate 'Details' %}</a
              >
            </div>
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/menu.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Кафе Яство-меню{% endblock %}

{% block content %}

<div class="d-flex justify-content-center">
  <ul class="bxslider ">
    <li><img src="{% static 'main/img/menu_pages/page-0001.jpg' %}"></li>
    <li><img src="{% static 'main/img/menu_pages/page-0002.jpg' %}"></li>
    <li><img src="{% static 'main/img/menu_pages/page-0003.jpg' %}"></li>
    <li><img src="{% static 'main/img/menu_pages/page-0004.jpg' %}"></li>
    <li><img src="{% static 'main/img/menu_pages/page-0005.jpg' %}"></li>
    <li><img src="{% static 'main/img/menu_pages/page-0006.jpg' %}"></li>
    <li><img src="{% static 'main/img/menu_pages/page-0007.jpg' %}"></li>
  </ul>
</div>
{% endblock%}

main/templates/main/shop.html
{% extends 'main/layout.html' %}
{% block title %}Магазин{% endblock %}

{% block content %}
{% endblock %}